site_title: LLM Project Portfolio - David Klan
site_title_ja: LLMプロジェクトポートフォリオ - David Klan
owner_name: David Klan
owner_role: IT PM + AI/ML Engineer
owner_role_ja: ITプロジェクトマネージャー + AI/MLエンジニア
hero_tagline: The interface between human intent and machine intelligence
hero_tagline_ja: 人間の意志と機械知性の接点
summary: I build the systems where human judgment meets artificial cognition — practical LLM architectures that know their own limits.
summary_ja: 人間の判断力と人工知能が交差するシステムを構築 — 自らの限界を知る実用的なLLMアーキテクチャ。
about_short: Agents, prompts, retrieval architectures, and automation woven together — because the most interesting outcomes emerge at the intersection of structured intent and machine intuition.
about_short_ja: エージェント、プロンプト、検索アーキテクチャ、自動化を織り合わせて — 構造化された意図と機械の直感が交差する場所から、最も興味深い成果が生まれます。
contacts:
  github: https://github.com/davidklan-png
  linkedin: https://www.linkedin.com/in/david-klan/
  website: 
  email: admin@dazbeez.com
skills:
  - name: Prompt Engineering
    name_ja: プロンプトエンジニアリング
    icon: prompt
  - name: RAG
    name_ja: RAG
    icon: rag
  - name: Agentic Workflows
    name_ja: エージェントワークフロー
    icon: workflow
  - name: Change Enablement
    name_ja: 変革マネジメント
    icon: change
  - name: Python/Automation
    name_ja: Python/自動化
    icon: python
  - name: Evaluation
    name_ja: 評価
    icon: evaluation
now_next:
  now:
    - Deepening JTES domain coverage for Japanese tax workflows.
    - Upgrade development infrastructure to build out services
  now_ja:
    - 日本の税務ワークフロー向けJTESドメインカバレッジの拡張。
    - サービス構築のための開発インフラのアップグレード
  next:
    - JTES beta with tax professionals and structured feedback cycles.
    - Implement OCR for automated receipt processing.
  next_ja:
    - 税理士との構造化されたフィードバックサイクルによるJTESベータ版。
    - レシート処理の自動化のためのOCR実装。
project_order:
  - receipt_classification_matching
  - jtes_specialized_rag
  - bilingual_ceremony_script_generator
  - enterprise_ai_enablement_insurance
