site_title: LLM Project Portfolio - David Klan
owner_name: David Klan
owner_role: Senior AI/ML Engineer
hero_tagline: Portfolio at a glance 
summary: I'm an IT Project Manager designing practical LLM systems.
about_short: I utilize multiple agents, prompt engineering, RAG architecture, and automation to deliver measurable AI outcomes.
contacts:
  github: https://github.com/davidklan-png
  linkedin: https://www.linkedin.com/in/david-klan/
  website: 
  email: admin@dazbeez.com
skills:
  - name: Prompt Engineering
    icon: prompt
  - name: RAG
    icon: rag
  - name: Agentic Workflows
    icon: workflow
  - name: Change Enablement
    icon: change
  - name: Python/Automation
    icon: python
  - name: Evaluation
    icon: evaluation
now_next:
  now:
    - Deepening JTES domain coverage for Japanese tax workflows.
    - Upgrade development infrastructure to build out services
  next:
    - JTES beta with tax professionals and structured feedback cycles.
    - Implement OCR for automated receipt processing.
project_order:
  - receipt_classification_matching
  - jtes_specialized_rag
  - bilingual_ceremony_script_generator
  - enterprise_ai_enablement_insurance
